### ISSUE TITLE
Colorization of Black and White Images

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/DeepPixel#1]

**Comment by purva98** [comment]
Hello @smaranjitghose , I had a small doubt. Should I use VGG16, since you have used it in your code, Or should I use some other pre trained model?

**Comment by purva98** [comment]
Hello, I am Purva. In your current code you have used VGG as the pre-trained model. For implementing this task, should I follow the same steps and use VGG, or should I use any other model? Thanks :)

**Comment by suhriddatta** [comment]
No there is no restriction ..you can train it on any model and test the
results

**Comment by purva98** [comment]
Thankyou
