### ISSUE TITLE
Photo Effects 

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/DeepPixel#118]
- You may or may not use Deep Learning for this

# Suggested Tasks:

- [ ] Cartoonify
- [ ] Oldify
- [ ] Black and White to Color
- [ ] Pencil Sketch - Black and White
- [ ] Pencil Sketch - Color
- [ ] Oil Painting
- [ ] Water Color
- [ ] Pointilism

# References:

- [ArtCV](https://github.com/smaranjitghose/ArtCV)
- White Box Cartoonization: [GitHub](https://github.com/SystemErrorWang/White-box-Cartoonization), [YoutTube Explanation](https://www.youtube.com/watch?v=eTMGoXgq6uM), [Paper](https://openaccess.thecvf.com/content_CVPR_2020/papers/Wang_Learning_to_Cartoonize_Using_White-Box_Cartoon_Representations_CVPR_2020_paper.pdf)

** For now, we prefer to use TensorFlow [ Later on we will include support for PyTorch as well]

**Comment by geekquad** [comment]
Hey, I would like to work on the Pencil Sketch - Black and White issue.

**Comment by sharur7** [comment]
Hello @smaranjitghose , I would like to work on Cartoonify task.

**Comment by bolt25** [comment]
I would like to work on oil painting

**Comment by ankit3699** [comment]
I am interested in working on Pencil Sketch - Color issue.

**Comment by simanfathima** [comment]
Hello @smaranjitghose I would like to work on Black and White to Color issue.

**Comment by Ajay0511** [comment]
I would like to work on pointillism.

**Comment by AyushSatyam** [comment]
I would like to work on watercolour issue.

**Comment by anut123** [comment]
I would like to work on Cartoonify issue

**Comment by smaranjitghose** [comment]
> I would like to work on Cartoonify issue

Assigned to @sharur7 for 6 more days

**Comment by anut123** [comment]
I would like to work on Oldify issue

**Comment by anut123** [comment]
I would like to work on Oldify issue

**Comment by saidrishya** [comment]
Hi, I would like to work on Black and White to Color.
