### ISSUE TITLE
Rock,paper and Scissor Game Implmentation

### ISSUE THREAD

**Issue by Shweta0002** [smaranjitghose/DeepPixel#17]
**Description** :
Have to identify the three hand  gestures i.e Rock , Paper and Scissor and create a  game .
**Difficulty**: Medium
**Implementation** : 
Neural Netwrok/MLP/logistic Regression ,OpenCV threshold can be used .

**Comment by Shweta0002** [comment]
I would like to work on it, so @smaranjitghose please assign this to me.

**Comment by smaranjitghose** [comment]
Please push it to ```test-branch```

**Comment by ysampriti** [comment]
I would like to work on this issue so please assign this to me.
