### ISSUE TITLE
Super Resolution

### ISSUE THREAD

**Issue by suhriddatta** [smaranjitghose/DeepPixel#19]
# Task
- Input: Take a small, low-resolution image
- Output: Give a high-resolution image without the formation of additional artifacts

For starting out, check out  the following and play around there before contributing the final scripts here :

[DeepPixelate](https://github.com/smaranjitghose/DeepPixel)

**Please don't use APIs**

**Comment by kritika12298** [comment]
I would like to work on this issue as I already worked on image denoising. Please assign this issue to me.

**Comment by suhriddatta** [comment]
Pls go through implementations of different image-enhancing methods , it will be helpful for you

**Comment by suhriddatta** [comment]
pls go through various image-enhancing methods , you will get an idea of how to proceed

**Comment by kritika12298** [comment]
Okay

**Comment by smaranjitghose** [comment]
Try to implement various architectures like SRGAN,ESRGANs

The best uptil now:
USRNET,USRGAN

**Comment by kritika12298** [comment]
Okay!
Thank you!

**Comment by kritika12298** [comment]
@smaranjitghose, I was working on this issue but now as you have closed it so should I continue with it or not?

**Comment by smaranjitghose** [comment]
Sure, you can continue with this, but please first finish off with the one I assigned you

**Comment by kritika12298** [comment]
Okay
