### ISSUE TITLE
Image Similarity

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/DeepPixel#21]
# Task
Compare two input images and return a value that tells how visually similar the given images are. The lower the score, the more contextually similar the two images are with a score of '0' being identical.

**Comment by annu12340** [comment]
I would like to work on this issue. Please assign it to me

**Comment by smaranjitghose** [comment]
@annu12340  has done the preliminary work to build on 👌
For the next phase of the issue, I want you to modify the script or add another one so that if I have an image say ``` img1 ``` and there's another image say ``` img2``` which is actually a part of the first image ```img1``` (consider I have a fingerprint as my first image and a part(say quadrant) of the fingerprint as the second image), our script should be able to identify this with a score and also draw a bounding box over the original image ```img1``` that tells us which part was taken to form ```img2``

**Comment by purva98** [comment]
Hi @smaranjitghose,
I was trying to understand, the next phase of this issue. I tried writing a script for it.
I wanted to confirm, if I am understanding the problem statement correctly, 
I am getting this output..is this how it should be?
![Screenshot (376)](https://user-images.githubusercontent.com/24644158/78149693-e7e6ed80-7453-11ea-92eb-24230c176db4.png)

**Comment by annu12340** [comment]
Hey Purva, I had modified the model, to detect the difference between the 2 images and to highlight these difference also

**Comment by purva98** [comment]
Ohh okay😂😂
I thought the next phase was, To find whether a small image was a subset of another large image. And then locate the smaller image in the larger image, and draw a bounding box. 
Lol, I think I messed up understanding the problem statement😂😂😂 Sorry!

**Comment by annu12340** [comment]
Purva, I am not sure about that. Just thought of informing you about the update :smile:

**Comment by smaranjitghose** [comment]
@purva98 I think this might work for a lot of cases, can you please share the link of the Colab Notebook

**Comment by smaranjitghose** [comment]
@annu12340 could you please share a snapshot of your work or the main highlight of you script

**Comment by purva98** [comment]
Hello @smaranjitghose ,
the link of the small script is [https://colab.research.google.com/drive/1ptEj1hWNAec_Nfn8Zp9B2e1cgrwlYx2Y](url)
Please let me know, if I should also include : Detection of multiple instances of the subset in larger image.

**Comment by smaranjitghose** [comment]
Yes, this is really nice
And you can start working for detecting multiple instances too

**Comment by purva98** [comment]
hello @smaranjitghose ,
in this file, i have implementation of single instance detection, followed by multiple instance detection, 
https://colab.research.google.com/drive/1ptEj1hWNAec_Nfn8Zp9B2e1cgrwlYx2Y
should I make a script and do a PR?

**Comment by smaranjitghose** [comment]
Yes, this works well!
Go ahead and give a PR for this and continue with the script.
Also, make sure you use a separate directory for this say ```img_subset```
