### ISSUE TITLE
Facial Expression Recognition

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/DeepPixel#22]

**Comment by riddhi99** [comment]
Thanks for your confirmation. I will start working on this feature.

**Comment by purva98** [comment]
Please assign this issue to me as well. My team mate has slow net connectivity these days,  so I ll coordinate with her, complete the remaining work. Thank you for understanding :)

**Comment by purva98** [comment]
Hello @smaranjitghose 
We created a CNN model and saved it...
To take in user inputs, should we take input as face images, or take input Real time from webcam..
what do you suggest..

**Comment by smaranjitghose** [comment]
Test it using input images for now, in a later PR, add a script for taking the video feeds using imutils
