### ISSUE TITLE
Real Time Pose Detection

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/DeepPixel#23]
# Task:
The function should access a webcam or feed any video and estimate the position of a person based  upon their key joint positions

For reference: 
https://medium.com/tensorflow/real-time-human-pose-estimation-in-the-browser-with-tensorflow-js-7dd0bc881cd5

**Comment by jhalak27** [comment]
This sounds interesting. Could you provide some more description about this?

**Comment by smaranjitghose** [comment]
I have updated the description. Do let me know if you need more details

**Comment by preeti13456** [comment]
Interested to work.

**Comment by preeti13456** [comment]
Interested to work

**Comment by smaranjitghose** [comment]
my bad @preeti13456 ! Pardon me for the delay

**Comment by ysampriti** [comment]
Hey I would like to work on this issue. Please assign it to me.
