### ISSUE TITLE
Face Recognition

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/DeepPixel#24]
## The following functions are to be included in this module:
- Input an image and output the image with faces detected (boundary boxes are drawn)
- Count the number of faces detected
- Real-Time Face Detection
- A pre-trained model(like MobileNet) that takes in a custom dataset of faces and recognizes the faces with labels in other images
- Get the gender and age

## Guidelines:

- Create a sub-directory ```face_rec``` inside the ```deeppixel``` directory and put your work there
- I would recommend giving multiple PRs for scripts solving one issue at a time..Please name them judiciously
- For the final scripts try to use [argparse](https://docs.python.org/3/library/argparse.html) library so that the input image and the output path can be given as arguments in the terminal while running the script along with other relevant parameters
- Comment your script/notebook well
- Make sure you have the model weight or any related files to run the script in the same directory
- Initially, you can try with images from Unsplash or other sources on the internet, however later on its better that you try to provide your own images and the corresponding outputs.
- Have two separate sub-directories ```input``` and ```output``` under an ```assets``` directory for the issue you are working on to save the images/videos(as applicable)
- Create/Update the ReadME.MD file:
    - Name of the task
    - A small description
    - Approach used
    - Input and Output Images
-  Create a ```requirements.txt``` file and specify the packages to be used
- In your PR, please try to give a link to a Colab Notebook(if applicable)  as a comment.
__Make sure its accessible by anyone when you share it 😅__
- In your PR, put a reference to the issue it is for
- Try to train deep learning models for this and surf through some latest related research papers and its implementations instead of using other packages like [scikit-image](https://pypi.org/project/scikit-image/) or [face-recognition](https://pypi.org/project/scikit-image/) so that our functions work for a lot of scenarios 

## References:

To start off you can play around  the following repos:
- [PyMukhra](https://github.com/smaranjitghose/PyMukhra)
- [PyMukhraBuild](https://github.com/smaranjitghose/PyMukhraBuild)

Feel free to contribute there if you wanna add on or change something

**Comment by jhalak27** [comment]
hey, I would like to work on this.

**Comment by smaranjitghose** [comment]
@jhalak27 Go ahead

**Comment by jhalak27** [comment]
Thanks!

**Comment by smaranjitghose** [comment]
@jhalak27 well done! 👌👌

Now I would like to have the face detection script working without using Haar Cascades (i.e. being trained on a face dataset or using some pre-trained deep learning models) to improve the accuracy

**Comment by jhalak27** [comment]
Yes, I am working on this. Please assign this to me.
