### ISSUE TITLE
Documentation of the project

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/DeepPixel#25]
Tasks:
- Work on the readme and make it more interactive and add on issues and other things from time to time
- Make sure the READMEs of the individual modules are synchronous
- Work on the  Github Page for this project ```gh-pages``` branch
- Learn and use [Sphinx](https://www.sphinx-doc.org/en/master/usage/quickstart.html) for actual documentation of this project as a package
- Make a template for Giving Pull Requests

**Comment by annu12340** [comment]
I would like to work on this

**Comment by jhalak27** [comment]
I would like to help with this.

**Comment by smaranjitghose** [comment]
@annu12340 can you make a ```gh-pages``` branch on your forked repository, delete all the other stuff and  keep only the website related files in that branch and give a Pull- Request to the ```gh-pages``` branch of this repository

**Comment by annu12340** [comment]
ok
