### ISSUE TITLE
Object Detection

### ISSUE THREAD

**Issue by jhalak27** [smaranjitghose/DeepPixel#32]
**Task:** A script to detect objects in a given image.
Input: Path to the image
Output: Image with objects detected and labelled along with boundary boxes 

**Future work:** 
Implementing real-time object detection.

**Comment by annu12340** [comment]
I would like to work on this issue

**Comment by smaranjitghose** [comment]
@jhalak27 Please provide an elaborate description of what the issue aims to achieve in the end and the various goals to be achieved on the go. Refer to the descriptions I have given for face_detection issues,etc

**Comment by jhalak27** [comment]
Should I add anything else to it?

**Comment by smaranjitghose** [comment]
Its fine for now

**Comment by jhalak27** [comment]
I am working for better pre-trained deep learning model

**Comment by smaranjitghose** [comment]
Cool..keep me updated
