### ISSUE TITLE
Music Genre Classification Using Deep Learning

### ISSUE THREAD

**Issue by purva98** [smaranjitghose/DeepPixel#39]
The Aim of this task, is to take input a music file, and perform the task of classification. The script should be able to predict the genre of the music. For example, pop, metal, jazz, classical, folk etc.

**Comment by preeti13456** [comment]
Interested to contribute.

**Comment by preeti13456** [comment]
Is it included in rgsoc ?

**Comment by smaranjitghose** [comment]
@purva98 Please put up a detailed description

@purva98  @purva98 
You are welcome to go ahead with this.

I would suggest having the script as genre_class.py that takes in a mp3 file and gives us the prediction in the terminal itself

Meanwhile work using Google Colab and share the notebooks for feedback as you optimize model training

Also, specify the genres you are taking into account, as well as the language in which the song is in

**Comment by preeti13456** [comment]
Interested to contribute.

**Comment by purva98** [comment]
@smaranjitghose Yes, I will keep sharing the google Colab notesbooks, to get the feedback, and improve accordingly.
