### ISSUE TITLE
Implement Denoising of Colored Images

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/DeepPixel#4]
Do it inside the sub-directory:
https://github.com/smaranjitghose/DeepPixel/tree/master/deeppixel/denoise

Try to take in your own images and apply the same.

Make sure you upload the images used in a images folder

A jupyter notebook is preferred but a script works well too

Please comment each part of your code, explaining why it's used so that others can use this as a groundwork for future work

**Comment by kritika12298** [comment]
Hello, I am Kritika Gupta, from team Warriors. Please assign this issue to me.

**Comment by mj2799** [comment]
I would like to work on this issue, can you please assign it to me
