### ISSUE TITLE
Instance Segmentation of images and videos

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/DeepPixel#48]

**Comment by Shweta0002** [comment]
@smaranjitghose I have made a PR for it and implemented it by going through the facebookAI research paper , which I have mentioned in my  README.md . Have a look please .

**Comment by smaranjitghose** [comment]
Definitely, I'll review it. Could you please share the link of the Jupyter notebook with me

**Comment by Shweta0002** [comment]
https://colab.research.google.com/drive/186YyuvwprCAIBm0wPh_YLfqc2PKopGjg

here's the link, have a look.

**Comment by smaranjitghose** [comment]
You seem to have forgotten to give open access rights for the notebook😅

**Comment by Shweta0002** [comment]
https://colab.research.google.com/drive/1CSQNr5G4q1-xfisvGCp8deglhhMtQmLf

sorry for that , you can check again.

**Comment by smaranjitghose** [comment]
Cool! create a script for it
