### ISSUE TITLE
Implement Face Detection in Pictures

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/DeepPixel#5]
# Task:
Input: Any image
Output: The image with faces detected 

# Further Work:
The function should return the resulting image with the number of faces detected

**Comment by jhalak27** [comment]
Hey, I want to work on this. Could you let me know more specification on what I have to do?

**Comment by smaranjitghose** [comment]
Here I want the input to be the path of an image and the output to be the image with different faces detected (bounding boxes drawn)

**Comment by jhalak27** [comment]
I have completed this. Please let me know if I should still make a PR.
