### ISSUE TITLE
Panoptic Segmentation of Images and Videos

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/DeepPixel#50]
Panoptic segmentation unifies the typically distinct tasks of semantic segmentation (assign a class label to each pixel) and instance segmentation (detect and segment each object instance).

To get started,
[Refer this link](https://medium.com/@danielmechea/what-is-panoptic-segmentation-and-why-you-should-care-7f6c953d2a6a)

**Comment by RevathiKannanGithub** [comment]
We would like to work on this issue, as part of rgsoc. Could you please provide more details about it.

**Comment by RevathiKannanGithub** [comment]
And could you please assign this to us?

**Comment by smaranjitghose** [comment]
Sure!
I have updated the description and also given a more detailed link to refer to. If you need something more, do let me know
