### ISSUE TITLE
Music Generation using RNN,LSTM

### ISSUE THREAD

**Issue by purva98** [smaranjitghose/DeepPixel#53]
The Aim of this task will be to, generate music with the help of recurrent networks. The model will be trained on various music samples/notes. As the output, it is expected that model generates new music notes.

**Comment by smaranjitghose** [comment]
I am creating another branch ```audio```, from the next update please push it there

**Comment by Prachi-Agr** [comment]
I am interested to work on this. Could you provide some references to begin with?
