### ISSUE TITLE
Text Recognition in Images 

### ISSUE THREAD

**Issue by annu12340** [smaranjitghose/DeepPixel#54]
The script should detect the text in images automatically

**Comment by smaranjitghose** [comment]
Try implementing it on different images where the background varies a lot and use cases like where there's a text written on a large wall behind a person

**Comment by annu12340** [comment]
:thumbsup:

**Comment by bharati-21** [comment]
Me and my team mate would like to work on this through RGSoC.

**Comment by annu12340** [comment]
Hi @bharati-21 , I am already working on this issue 😃
