### ISSUE TITLE
Implement Image Illumination

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/DeepPixel#6]

**Comment by purva98** [comment]
Hello @smaranjitghose. I had a small query. Is Image Illumination related to 1. The capacity of increasing or decreasing the brightness of image , OR 2. The feature of image enhancement,
 Thanks

**Comment by smaranjitghose** [comment]
Hey @purva98 . For image illumination, I would prefer enhancement of the image.
For starters, you do refer: https://www.pyimagesearch.com/2015/10/05/opencv-gamma-correction/

**Comment by purva98** [comment]
Great, thanks

**Comment by purva98** [comment]
I wish to make a input folder containing 20-25 images. The size of the images is large. Is it okay if I put a google drive link for people to download the input images folder from there?

**Comment by smaranjitghose** [comment]
Even if its 50MB, when you git push it should just show a warning and work well. Ya, you can do that too
