### ISSUE TITLE
Diseased Leaf Classification

### ISSUE THREAD

**Issue by kritika12298** [smaranjitghose/DeepPixel#64]
Pull-Request to Test Branch

**Comment by kritika12298** [comment]
Classifying leaves of diseased on non diseased plants.

**Comment by smaranjitghose** [comment]
What dataset are you planning you use for this?

**Comment by kritika12298** [comment]
Plant Dataset from Kaggle.

**Comment by kritika12298** [comment]
Its name is PlantVillage Dataset and I'll be implementing a research paper
on it in which I'll be extracting shape, texture and color using global
feature extraction techniques.

**Comment by smaranjitghose** [comment]
Cool, Go ahead!
