### ISSUE TITLE
 Artistic Style Transfer

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/DeepPixel#7]
# Task 
 Take input a content image,style image and  ]output a image that transfers the style into the content image

# Guidelines:
- Experiment building this using a Jupyter notebook locally or on [Google Colab](https://colab.research.google.com/)
- Once its giving desired results put it inside the ```artistic_style_transfer ``` directory
- Build a script for the task inside the ```bw_to_c ``` directory
- Inside the ```artistic_style_transfer``` directory, create two folders ```input``` and ```output``` to be used for the input and output images
- Use [argparse](https://docs.python.org/3/library/argparse.html) library so that the input image and output path can be given as arguments in the terminal while running the script
-  Create a ```requirements.txt``` file and specify the modules used
- Try your script/notebook with multiple images and store the results in output folder
- Comment your script/notebook well
- Create/Update the ReadME.MD file:
    - Name of the task
    - A small description
    - Approach used
    - Input and Output Images
- Make sure you have the model weight or any related files to run the script in the same directory
- Push the changes and give a Pull Request
- In your PR, please try to give a link to a Colab Notebook(if applicable)  as a comment.
- In your PR, put a reference to the issue it is for
- once your model/script works, curate your own dataset and get the outputs..(Try 10 images) and give a second PR about your own Dataset
- Try out other methods to implement the above

**Please do not use a code from someone else's repo or a blog like PyImageSearch directly..You can definitely refer to others' code. But make sure you make some contributions of your own into it. If you strongly use a code from someone else,please credit them properly in the README file.**

**Comment by Shweta0002** [comment]
Hi , I want to do this one , but can you provide a bit more details?

**Comment by suhriddatta** [comment]
can you specify what do you need??

**Comment by Shweta0002** [comment]
the artistic style transfer code is already there in repo , so  what we are expected to do? do we have to implement it in some other way ?

**Comment by smaranjitghose** [comment]
Actually, that was provided as a sample for you all to get started with
For starters, you can build a script out of it 
Also do some digging on some better methods for the same..
See:https://github.com/smaranjitghose/DeepHoli
Here we took NVIDIA's State of the Art Approach and implemented it

**Comment by purva98** [comment]
@smaranjitghose , is anyone still working on this issue. Else can you please assign this issue to me?

**Comment by srishti0908** [comment]
We have run the existing code on Google Colab and have obtained the desired output. You mention that the next step is to "Build a script for the task inside the bw_to_c directory". Is this a typo from the Black and White to Color task? Shall we build a script in artistic_style_transfer directory?

**Comment by smaranjitghose** [comment]
Yes, please build it in ```artistic_style_transfer``` directory. Sorry, my bad it was  a typo

**Comment by smaranjitghose** [comment]
Yes, please build it in ```artistic_style_transfer``` directory. Sorry, my bad it was  a typo

**Comment by srishti0908** [comment]
Thank You

**Comment by srishti0908** [comment]
We would like you to assign this issue to me and @RupaliBhati

**Comment by smaranjitghose** [comment]
Please ask her to comment so that I can comment

**Comment by RupaliBhati** [comment]
Hi Smaranjit, kindly assign this problem to me. Thanks!

**Comment by Prachi-Agr** [comment]
I would like to work on this issue. Kindly assign it to me.

**Comment by smaranjitghose** [comment]
Its already being assigned to people, could you instead work on photorealistic style transition?

**Comment by Prachi-Agr** [comment]
Yes. I can do that.
