### ISSUE TITLE
Image Super-Resolution

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/DeepPixel#71]
# Task:
Take in a low very low-resolution image and output an enlarged and high resolution image

# Suggested workflow:

- Inside the ```deeppixel``` directory, create a new sub-directory ```img_super_res```__[Please name it appropriately and use [camel_case](https://medium.com/better-programming/string-case-styles-camel-pascal-snake-and-kebab-case-981407998841)]__
- In the first attempt 💭💭 use a [Jupyter notebook] to perform your work.  
- Once you are done give a Pull Request🩹 with the message 📩```Developed Jupyter Notebook for Image Super-Resolution```, briefing about your approach in the description and add a link of the above notebook in [Google Colab](https://colab.research.google.com/) __[Please ensure you have given access]__ ⛔
- Once merged😎 , build a script for the same task in the ```img_super_res``` directory __(If you are using Deep Learning, ensure that you have saved your trained model and its weights so that in the script you build can simply fetch it instead of training again)
- Use [argparse](https://docs.python.org/3/library/argparse.html) library so that the input image and the output path can be given as arguments in the terminal while running the script
- Update the ```requirements.txt``` file in the root directory of the master branch to ensure any additional modules you have used in present there.
- Make sure you provide sample images/videos 📷 used
- Give a Pull Request 🩹 with the message 📩```Developed Script for Image Super-Resolution``` and mention how you have given the argument parameters to run the script in the description 
- Once approved, work on documenting every block of code if not every line of your script 
- Add a ```README.MD``` file with appropriate description __[Please ensure you properly cite any research paper or blog you have taken direct reference from]__ 
- Give another Pull Request 🩹 with a message 📩 : ```Documentation Updated for Image Super-Resolution``` 

# References :

Will be updated  with more soon, Meanwhile, feel free to try these

- ESRGAN: Enhanced Super-Resolution Generative Adversarial Networks
  - [Paper](https://arxiv.org/pdf/1809.00219v2.pdf)
  - [Available Implementation in TensorFlow](https://github.com/peteryuX/esrgan-tf2)
  - [Available Implementation in PyTorch](https://github.com/eriklindernoren/PyTorch-GAN#enhanced-super-resolution-gan)

- Second-Order Attention Network for Single Image Super-Resolution
  - [Paper](http://openaccess.thecvf.com/content_CVPR_2019/papers/Dai_Second-Order_Attention_Network_for_Single_Image_Super-Resolution_CVPR_2019_paper.pdf)
  - [Available Implementation](https://github.com/daitao/SAN)

-  Image Reconstruction with Predictive Filter Flow
    - [Paper](https://arxiv.org/pdf/1811.11482v1.pdf)
    - [Available Implementation](https://github.com/aimerykong/predictive-filter-flow)

# Additional Tasks: 

- Curate a custom dataset 🧰 for this task
-  Look for better methods to improve 🥇 this

**Comment by Prachi-Agr** [comment]
I would like to work on this. Kindly assign this to me.

**Comment by smaranjitghose** [comment]
@Prachi-Agr Please keep us updated on your work in the slack channel in case you need to share the notebooks or need some feedback
