### ISSUE TITLE
UI/UX Tasks

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/DeepPixel#82]
# Task:
- Create a custom logo for deeppixel taking into consideration the themes of deep learning, open source and tech 
  - Name it as ```deeppixel_icon.jpeg```
  - Please provide a high-resolution image as well as an icon
  - change your branch to gh-pages and put it inside the assets folder
  - Give a Pull Request to this repo's gh-pages branch
- Create a template image  for the GitHub repo in accordance to the above theme
   - Image size should be 1280×640px 
  - Name it as ```deeppixel_template.jpeg```
  - change your branch to ```gh-pages``` and put it inside the assets folder
  - Give a Pull Request to this repo's ```gh-pages``` branch

**Comment by annu12340** [comment]
I would like to work on this

**Comment by purva98** [comment]
Hello, can I and my teammate work on this?
