### ISSUE TITLE
GitHub Actions for this project

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/DeepPixel#83]
# Task:
Create custom GitHub Actions or use pre-existing ones to automate the workflow for this project

**Comment by minolipvartak** [comment]
I would like to work on this @smaranjitghose

**Comment by smaranjitghose** [comment]
Minoli before giving PRs, please have a discussion with me or the other mentors in the respective channel on Slack, so that we can figure the most appropriate actions for this project and also analyze the tradeoff for using similar GitHub apps from the GitHub marketplace. If you need to experiment this, feel free to give a PR to any of my repos like ```DeepHoli```

**Comment by minolipvartak** [comment]
Yes👍
