### ISSUE TITLE
Face Anonymization  (Face Blurring)

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/DeepPixel#84]
# Task:
Blur the faces in an image as well as video

# Suggested workflow:

- Inside the ```deeppixel``` directory, create a new sub-directory ```face_blur```__[Please name it appropriately and use [camel_case](https://medium.com/better-programming/string-case-styles-camel-pascal-snake-and-kebab-case-981407998841)]__
- In the first attempt 💭💭 use a [Jupyter notebook] to perform your work.  
- Once you are done give a Pull Request🩹 with the message 📩```Developed Jupyter Notebook for Face Blur``` , briefing about your approach in the description and add a link of the above notebook in [Google Colab](https://colab.research.google.com/) __[Please ensure you have given access]__ ⛔
- Once merged😎 , build a script for the same task in the ```face_blur ``` directory __(If you are using Deep Learning, ensure that you have saved your trained model and its weights so that in the script you build can simply fetch it instead of training again)
- Use [argparse](https://docs.python.org/3/library/argparse.html) library so that the input image and the output path can be given as arguments in the terminal while running the script
- Update the ```requirements.txt``` file in the root directory of the master branch to ensure any additional modules you have used in present there.
- Make sure you provide sample images/videos 📷 used
- Give a Pull Request 🩹 with the message 📩```Developed Script for Face Blur``` and mention how you have given the argument parameters to run the script in the description 
- Once approved, work on documenting every block of code if not every line of your script 
- Add a ```README.MD``` file with appropriate description __[Please ensure you properly cite any research paper or blog you have taken direct reference from]__ 
- Give another Pull Request 🩹 with a message 📩 : ```Documentation Updated for Face Blur``` 
- Now save the model and the model weights, build a single python script that takes in an image and gives us the output (Make sure the model and model weight is properly named for future use) by using your already trained model

# References:

- [PyImageSearch blog](https://www.pyimagesearch.com/2020/04/06/blur-and-anonymize-faces-with-opencv-and-python/)

# Additional Tasks: 

-  Curate a custom dataset 🧰 for this task
-  Look for better methods to improve 🥇 this

**Comment by Shweta0002** [comment]
I want to work on this @smaranjitghose ,but can you make it clear , the description have two things, title says we have to develop a face blurring script and description says enhancement of low light images. So do we have to work on both?

**Comment by smaranjitghose** [comment]
Sorry, there was a glitch in the description, its is for face blur only

**Comment by Shweta0002** [comment]
Oh ok , Then I am working on this , kindly assign this to me.

**Comment by jhalak27** [comment]
Hey, can I also work on this?

**Comment by smaranjitghose** [comment]
Sure

**Comment by smaranjitghose** [comment]
@Shweta0002 for this issue Jhalak has done the groundwork, you can build on it:
- By using better Face Detection models for optimized performance 
- Use object detection to ensure that if one holds an object in front of the face(say drinking water from a water bottle), our script takes the last known location of the face (i.e., the previous detection location) and then blurs that region instead of the current issue of missing the face detection.
- Collaborate with Jhalak on the GAN approach I have referred to in the slack channel (will update the description soo)

Keep me updated in the slack channel
