### ISSUE TITLE
 Personal Protective Equipment (PPE) detection

### ISSUE THREAD

**Issue by ritu01rt** [smaranjitghose/DeepPixel#86]
#Task:
To detect workers with proper PPE and those without PPE for work safety.

**Comment by smaranjitghose** [comment]
What data set are you planning to use for this?

**Comment by ritu01rt** [comment]
I will prepare my own dateset mostly from google search and existing local dataset. Meanwhile, I also have existing dataset from AIMIR( Artificial Intelligence for Multimedia Information Retrieval) which will serve my purpose to train my implemented code. I will annotate my own image dataset in pascal VOC format using the awesome lightweight annotation tool Labellmg for object detection

**Comment by smaranjitghose** [comment]
I had attempted something similar but due to improper dataset the accuracy was not high enough, I would love to see your work on this. Go ahead. Keep me updated on the slack channel. If your model performs well, we can deploy it using tfjs.

**Comment by ritu01rt** [comment]
Thankyou so much! Will keep you updated about the works.
