### ISSUE TITLE
Black and White to Color 

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/DeepPixel#9]
# Task 
 Take input a black and white and output a realistic color image

# Guidelines:
- Experiment building this using a Jupyter notebook locally or on [Google Colab](https://colab.research.google.com/)
- Once its giving desired results put it inside the ```bw_to_c ``` directory
- Build a script for the task inside the ```bw_to_c ``` directory
- Inside the ```bw_to_c``` directory, create two folders ```input``` and ```output``` to be used for the input and output images
- Use [argparse](https://docs.python.org/3/library/argparse.html) library so that the input image and output path can be given as arguments in the terminal while running the script
-  Create a ```requirements.txt``` file and specify the modules used
- Try your script/notebook with multiple images and store the results in output folder
- Comment your script/notebook well
- Create/Update the ReadME.MD file:
    - Name of the task
    - A small description
    - Approach used
    - Input and Output Images
- Make sure you have the model weight or any related files to run the script in the same direcorty
- Push the changes and give a Pull Request
- In your PR, please try to give a link to a Colab Notebook(if applicable)  as a comment.
- In your PR, put a reference to the issue it is for
- once your model/script works, curate your own dataset and get the outputs..(Try 10 images) adn give a second PR about your own Dataset
- Try out other methods to implement the above

**Please do not use a code from someone else's repo or a blog like PyImageSearch directly..You can definitely refer to others' code. But make sure you make some contributions of your own into it. If you strongly use a code from someone else,please credit them properly in the README file.**

**Comment by gayathri-venu** [comment]
Is this issue still open?

**Comment by purva98** [comment]
@smaranjitghose I am hoping to still add a few more parts to the script. To avoid any confusions, can you please assign this issue to me :)
